services:
  node-red:
    build:
      context: ./NodeRed/ConfigurationFiles
    container_name: node-red
    user: "0"
    privileged: true
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Brussels
      - ONDULEUR-IP=192.168.30.8
      - P1READER-PORT=/dev/ttyUSB0
    ports:
      - "1880:1880"
    devices:
      - /dev/gpiomem
    volumes:
      - ./NodeRed/Data:/data
    group_add:
      - dialout
  
#  cloudflared:
#    container_name: cloudflared
#    image: cloudflare/cloudflared
#    restart: unless-stopped
#    command: tunnel run
#    environment:
#      - TUNNEL_TOKEN=${CLOUDFLARED_TOKEN}
#    network_mode: host
